### ISSUE TITLE
Deprecation Warning about yaml.load()

### ISSUE THREAD

**Issue by renky** [nitmir/policyd-rate-limit#15]
Distribution: ubuntu 20.04
installed via apt
version: policyd-rate-limit_1.0.0-1_all.deb

policyd-rate-limit ist throwing a warning:
```
 /usr/lib/python3/dist-packages/policyd_rate_limit/utils.py:88: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self._config = yaml.load(f)
```

**Comment by P-EB** [comment]
@nitmir a preference between Loader=FullLoader or Loader=SafeLoader ?

**Comment by nitmir** [comment]
I'll say FullLoader.
It's should not be a security issue as we do not load user crafted yaml (only the config wrotten by the admin), and it do not change the current behavior in case someone load some python structure.

I, personally, do not use python extended yaml, so SafeLoader will also work with my config. What do you think ?

**Comment by renky** [comment]
From my point of view I think what's not needed doesn't need to be loaded... so if SaveLoader is enough, I'd prefer that - just my 2 cents

**Comment by P-EB** [comment]
Let's go for a SafeLoader then. :)

**Comment by kermit1981** [comment]
How to Fix policyd-rate-limit: Uses deprecated yaml.load error on Debian 12
https://www.tech2geek.net/fixed-policyd-rate-limit-uses-deprecated-yaml-load-error-on-debian-12/
The error “policyd-rate-limit: Uses deprecated yaml.load” on Debian 12 can be fixed by updating the PolicyD configuration to use the newer yaml.safe_load() function instead of the deprecated yaml.load(). Here’s how to resolve this issue:
1. Open the PolicyD configuration file:
sudo nano /usr/lib/python3/dist-packages/policyd_rate_limit/utils.py

2. Locate the line that uses yaml.load() and replace it with yaml.safe_load(). The modified line should look like this:
self._config = yaml.safe_load(f)
    Save the file and exit the text editor.
    Restart the PolicyD service to apply the changes:
sudo systemctl restart policyd
